### PR TITLE
Added support for specifying a timer name.  Timers with a timerName prop...

### PR DESCRIPTION
**Pull request by enragedginger**
...erty set will only respond to start, stop, resume, and clear events if the timer's name is specified on the event args.

This should allow for multiple timers of different purposes nested underneath a single controller.  This change only adds support for the start, stop, resume and clear events.  Adding support for the timer-set-countdown event looked like it would induce a breaking change, so I skipped it for now.

What are your thoughts on this?

### CODE REVIEW

**Comment by arun0009** [comment]
Is there a way to broadcast for multiple timers? I have multiple countdowns to display but                     $scope.$broadcast resets all the countdowns on my page.

**Comment by polomarcus** [comment]
Hi @arun0009,

I use this for example :
```javascript
        document.getElementById('chrono').getElementsByTagName('timer')[0].start();
        document.getElementById('chrono').getElementsByTagName('timer')[0].stop();
```

Of course, it would be better to use the angular way. In my opinion a service is the best way to perform it.

**Comment by NetanelBasal** [comment]
Can you update the docs or write here example how to use this feature? cause i have multiple timers in my page and i want to know in the timer-stopped event which one is stopped.

**Comment by cotufaloschiflones** [comment]
Hello, 

It's possible to add a name or id to each timer, not to hard. But I find this is not the proper solution, the correct way in my opinion is to create separate events/listeners for each one. What i'm doing now is just to set a name for each timer and then I have "like a kind of machine state" hearing for "timer-tick" event and depending on the name, I choose what I want to do, but I think this is a crappy solution.

If anybody has another solution I'm glad to her it!

**Comment by jrmyward** [comment]
Any movement on this? Either the timer element should be returned in the event args or this PR _should_ be accepted. 

The ability to handle timers independently seems like a pretty basic requirement. Anyone have a good workaround?

**Comment by flacohenao** [comment]
Any movement on this? i'm looking for a solution just like you guys, how did you solve that problem guys?

**Comment by enragedginger** [comment]
@siddii Any chance of this getting merged in?

**Comment by enragedginger** [comment]
Closing this due to lack of interest

**Pull request closed without merging**
