### PR TITLE
New plural unit decision functions

### PR DESCRIPTION
**Pull request by sanderai**
Removed singular units from zero-units and added new unit functions with custom string support for multilingual support.

Example usage in HTML:
English:
<timer>{{ minutes }} {{ minuteUnit('minute','minutes') }} {{ seconds }} {{ secondUnit('second','seconds') }}</timer>
Estonian:
<timer>{{ minutes }} {{ minuteUnit('minut','minutit') }} {{ seconds }} {{ secondUnit('sekund','sekundit') }}</timer>

### CODE REVIEW

**Comment by xaralis** [comment]
I'm afraid that current implementation is insufficient, for example in Czech language, there are more forms than just two. It would be nice if we could join this somehow with ng-pluralize in order to use current locale. Does someone has any idea how to go about this?

**Comment by polomarcus** [comment]
I work on the i18n of online alarm clock and MomentJS makes this really easy.
What do you think if we use MomentJS @siddii ? I could make a PR quite soon

More details :
http://momentjs.com/docs/#/i18n/

**Comment by siddii** [comment]
@polomarcus - Sounds good! Please send a PR.

**Comment by polomarcus** [comment]
@siddii My PR is almost ready. Waiting for another PR to be accepted : https://github.com/EvanHahn/HumanizeDuration.js/pull/40

I used MomentJS and HumanizeDuration to have a correct time display.

We will have 17 languages (https://github.com/EvanHahn/HumanizeDuration.js#supported-languages) available using the language attribut with a directive.

**Comment by siddii** [comment]
Awesome... Can you also add docs/sample code related this change?

**Comment by polomarcus** [comment]
That's already done with a Spanish and french example, and also e2e tests :)

**Pull request merged**
