### PR TITLE
Fix #125 - Invalid argument on IE

### LINKED ISSUE #125: Problem with IE11
The directive dont work well with ie and with chrome and firefox yes. he dosent display the time.
i get this error only in ie:

Error: Invalid argument.
 at Anonymous function (https://localhostvendor/angular-timer.min.js:57:24)

### PR DESCRIPTION
**Pull request by lukescott**
This fixes #125. The response on that issue suggests that using `<span ng-bind="foo">` vs `{{ foo }}` is a workaround. I could not get that working. It also links an issue regarding `$compile`.

I discovered the actual problem is setting properties on HTML nodes. In the code you have methods being added to `$element[0]`. IE does not like this. Since method already exist on `$scope`, I removed them from `$element[0]`.

This is at least a breaking change for #227. `$element[0]` was being set prior to this, but that PR added `timerElement` to the `timer-tick` event. I'm guessing the element is passed to access methods such as `pause`, `stop`, etc. But since these methods are already on the scope, wouldn't these methods already be accessible?

### CODE REVIEW

**Comment by siddii** [comment]
@lukescott  - Can you fix the build please?

**Comment by lukescott** [comment]
I wasn't expecting this to get merged without some discussion. Are you referring to timerElement, or something else?

**Comment by siddii** [comment]
I was referring to the Travis build - https://travis-ci.org/siddii/angular-timer/builds/201741784

I thought it was green. I guess I overlooked :(

**Comment by lukescott** [comment]
Yeah, sure. I missed the `grunt tests` part. I assumed it was `grunt test`.

Btw, you can setup Travis + Github to show test results on the PR and disable the merge button if the tests fail. I didn't see that on the PR, so I'm assuming it isn't currently setup that way.

**Comment by siddii** [comment]
It was setup that way. For some reason, either the lag of time or whatever, it was showing me green.

**Comment by lukescott** [comment]
@siddii See #298

**Pull request merged**
