### PR TITLE
Watching startTimeAttr and restarting timer if changed

### PR DESCRIPTION
**Pull request by leamagic**
If the timer is running and the startTimeAttr is changed, the timer will be restarted.

### CODE REVIEW

**Comment by mgoldsborough** [comment]
Great add. Thanks, @alduro!

@siddii, any timetable on a new release to bower?

**Comment by siddii** [comment]
Here is a new release - https://github.com/siddii/angular-timer/releases/tag/v1.2.1

**Comment by mgoldsborough** [comment]
Awesome.  Thanks, @siddii!

**Comment by mgoldsborough** [comment]
@siddii was the dist directory rebuilt for v1.2.1?  Still looks like v1.2.0.

**Comment by siddii** [comment]
Good point, I'll check

**Pull request merged**
