### PR TITLE
FIX: humanizer units format according to humanize-duration v3.1.0+

### PR DESCRIPTION
**Pull request by simonemazzoni**
Hello,
this PR resolve the issue that causes the library not to work properly with updated versions of humanize-duration as pointed in #222 

The fix is pretty simple as you can see from the code.

I also removed the `moment.locale(this.language)` line to prevent unwanted side effects on users moment.locale settings since it sets the language globally.

It is better to tell users to set the language themselves invoking a `moment.locale('wanted_language_code')` instead of force it from the directive.

Hope this is good with you.
Let me know if there are questions.

Please, can also update the npm package?

Thanks
Simone

### CODE REVIEW

**Comment by simonemazzoni** [comment]
Also please, consider to add `humanize-duration` as dependency since it is fundamental to make angular-timer works with i18n.

**Comment by simonemazzoni** [comment]
@siddii is possible to update the version to 1.3.5 with a tag and update also npm accordingly?

Thanks

**Comment by siddii** [comment]
@simonemazzoni - Its tagged and published on npm - https://www.npmjs.com/package/angular-timer

Sorry for the delay.

**Comment by simonemazzoni** [comment]
Great!! Thanks ;)

**Pull request merged**
