### PR TITLE
Momentjs - bower_components

### PR DESCRIPTION
**Pull request by polomarcus**
* bower_components in this branch
* Update angularJS to 1.3.14
* Suggest removing momentjs.local('lang') in i18nService

### CODE REVIEW

**Comment by siddii** [comment]
Yep, this looks much better. Merging it to master.

**Comment by siddii** [comment]
@polomarcus - Sorry to bug you again. Can you take a look at why `gh-pages` branch - http://siddii.github.io/angular-timer/ is broken?

**Comment by siddii** [comment]
OK, its fixed now. For some reason `gh-pages` branch didn't like `_timer.js`

**Comment by polomarcus** [comment]
Sorry I have just seen your message. Thanks for fixing the gh-pages. 

I will try to take a look on why the build is not passing on travis for the master branch today

**Pull request merged**
