### PR TITLE
Issue/180

### PR DESCRIPTION
**Pull request by evilaliv3**
With this pull request i've implemented the following:

1) first commit is a simple fix to issue 180
2) the other commits implement a more complete solution that would require HumanizeDuration to integrate https://github.com/EvanHahn/HumanizeDuration.js/pull/55

@EvanHahn here you can find the integration extension for [HumanizeDuration](https://github.com/EvanHahn/HumanizeDuration.js)

### CODE REVIEW

**Comment by EvanHahn** [comment]
`.getSupportedLanguages()` has been merged into the HumanizeDuration.js (as part of https://github.com/EvanHahn/HumanizeDuration.js/pull/55), so it might be worth re-running the CI build.

I didn't know about this library—glad to see someone integrating HumanizeDuration!

**Comment by evilaliv3** [comment]
great @EvanHahn thanks! @siddii what about integratin this pull now that all is ready? :)

**Comment by siddii** [comment]
@evilaliv3 - Can you fix the tests please?

**Comment by evilaliv3** [comment]
sure @siddii

**Comment by evilaliv3** [comment]
the issue was simply that we need to update the library. i'm going to test it!

**Comment by evilaliv3** [comment]
here you go! done! automagically the test will now work :)

**Pull request merged**
