### PR TITLE
i18N of the directive

### PR DESCRIPTION
**Pull request by polomarcus**
Feat
* Used momentJS and humanize-duration

Chrores
* Update angular with bower
* update .gitignore to remove bower_components and dist folders

Test
* update test for angular 1.3
* add e2e test for i18N

Doc
* update index.html for example purposes

### CODE REVIEW

**Comment by siddii** [comment]
This is cool. MomentJS integration was on my list but, didn't get time to work on. I think this opens up lot more possibilities with this module. Do you think its easy to sneak in `timeAgo` type feature into this module? 

```javascript
moment().endOf('day').fromNow();          // in 13 hours
moment().startOf('hour').fromNow();       // 17 minutes ago
```

Again, thanks so much for taking time to create this PR :+1: Truly appreciate your effort!

**Comment by polomarcus** [comment]
Correct me if I am wrong but we cannot use `.fromNow()` method due to momentjs time range, please see http://momentjs.com/docs/#/displaying/fromnow/

That's why I used humanize-duration actually.

**Comment by polomarcus** [comment]
Just seen that the CHANGELOG.md in the dist folder has been removed, I can add it to the root folder if you want to

**Comment by siddii** [comment]
Sure, thats a good idea.

**Comment by siddii** [comment]
Can you please update the markup with the language attribute & more info related to the change ?

screen shot 2015-02-18 at 6 59 52 am

**Comment by siddii** [comment]
Also.. examples files seems to be broken?

screen shot 2015-02-18 at 7 02 53 am

**Comment by polomarcus** [comment]
Yes sure, sorry about that I did not check the example.html file. Thanks for your review

**Pull request merged**
